name: UFT Automation Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-uft-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "Setting up environment for UFT..."
          # Add any commands to install dependencies here
          # For example, if you need to install specific software, do it here
          # Example: choco install <package-name> or any other installation commands

      - name: Debugging
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          dir
          echo "Environment variables:"
          set

      - name: Run UFT Automation Scripts
        run: |
          echo "Starting UFT automation scripts..."
          C:\Users\80012664\Documents\AutomationProject\QAutomationUFT\QAutomationUFT\UFTBatchRun.bat
          if ERRORLEVEL 1 (
            echo "UFTBatchRun.bat failed with error code %ERRORLEVEL%"
            exit /b %ERRORLEVEL%
          )
