name: UFT Automation Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-uft-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files in QAutomationUFT Directory
        run: |
          echo "Listing files in the QAutomationUFT directory:"
          dir .\QAutomationUFT

      - name: Run UFT Automation Scripts
        run: |
          echo "Starting UFT automation scripts..."
          .\QAutomationUFT\UFTBatchRun.bat
          if ($LASTEXITCODE -ne 0) {
            echo "UFTBatchRun.bat failed with error code $LASTEXITCODE"
            exit $LASTEXITCODE
          }
